jobs:
- name: lab-prep
  plan:
  - get: git-resource
    trigger: true
  - config:
      image_resource:
        name: ""
        source:
          repository: sconrod/python-aws-image
          tag: 2
        type: docker-image
      inputs:
      - name: git-resource
      platform: linux
      run:
        path: sh
        args:
          - -ce
          - |
            export AWS_PAGER=""
            aws configure set aws_access_key_id $AWS_KEY_ID
            aws configure set aws_secret_access_key $AWS_KEY
            aws configure set default.region $REGION
            aws sts get-caller-identity --query Account --output text
    task: check-aws
    params:
      AWS_KEY_ID: ((Access_key_ID.Access_key))
      AWS_KEY: ((Secret_access_key.Secret_access_key))
      REGION: ((aws.region))

- name: deploy-aws-env
  plan:
    - get: git-resource
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/python-aws-image
            tag: 2
          type: docker-image
        inputs:
          - name: git-resource
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              cd git-resource
              export AWS_PAGER=""
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              export SSH_TOKEN=$SSH_TOKEN
              echo $SSH_TOKEN
              chmod a+x aws_key_vault.sh
              chmod a+x aws_deploy.sh
              ./aws_key_vault.sh
              ./aws_deploy.sh
      task: build-vpc
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))
        SSH_TOKEN: ((ssh-token.token))

- name: deploy-csr1000v
  plan:
    - get: git-resource
      passed: [deploy-aws-env]
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/python-aws-image
            tag: 2
          type: docker-image
        inputs:
          - name: git-resource
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              cd git-resource
              export AWS_PAGER=""
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              chmod a+x csr_deploy.sh
              ./csr_deploy.sh
      task: build-csr1000v
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))

- name: deploy-ubuntu-lan
  plan:
    - get: git-resource
      passed: [deploy-aws-env]
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/python-aws-image
            tag: 2
          type: docker-image
        inputs:
          - name: git-resource
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              cd git-resource
              export AWS_PAGER=""
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              chmod a+x aws_ubuntu_lan_deploy.sh
              ./aws_ubuntu_lan_deploy.sh
              export
      task: build-ubuntu-lan
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))

- name: deploy-ubuntu-router
  plan:
    - get: git-resource
      passed: [deploy-aws-env]
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/python-aws-image
            tag: 2
          type: docker-image
        inputs:
          - name: git-resource
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              cd git-resource
              export AWS_PAGER=""
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              chmod a+x aws_ubuntu_router_deploy.sh
              ./aws_ubuntu_router_deploy.sh
      task: build-ubuntu-router
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))


- name: deploy-thousand-eyes-agents
  plan:
    - get: git-resource
      passed: [deploy-ubuntu-router]
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/netmiko
            tag: latest
          type: docker-image
        inputs:
          - name: git-resource
        platform: linux
        run:
          path: /bin/sh
          args:
            - -cex
            - |
              cd input
              chmod a+x thousandeyes/te_config/input/configure_te_agents.sh
              ./thousandeyes/te_config/input/configure_te_agents.sh
      params:
        SSHKEY: ((ssh_aws_key))
      task: deploy-thousand-eyes-agents

- name: deploy-appdynamics-agents
  plan:
    - get: git-resource
      passed: [deploy-ubuntu-router]
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/netmiko
            tag: latest
          type: docker-image
        inputs:
          - name: git-resource
        platform: linux
        run:
          path: /bin/sh
          args:
            - -cex
            - |
              cd input
              chmod a+x appdynamics/agent-installs/server-agent/input/configure_appd_agents.sh
              appdynamics/agent-installs/server-agent/input/configure_appd_agents.sh
      params:
        SSHKEY: ((ssh_aws_key))
      task: deploy-thousand-eyes-agents

resource_types:
resources:
  - name: git-resource
    source:
      Username: ((Username))
      branch: ((git-branch))
      email: ((email))
      private_key: ((private_key))
      uri: ((git-uri))
    type: git
