installClusterAgent: true
installInfraViz: true

# AppDynamics controller info
controllerInfo:
  url: https://mycontroller.saas.appdynamics.com:443
  account: mycontroller
  username: someuser
  password: somepassword
  accessKey: someaccesskey
  globalAccount: mycontroller_3j2f1w9o-2mdh-3719-bf5b-7147iiw8502c
  
# Cluster agent config
clusterAgent:
  nsToMonitorRegex: default

instrumentationConfig:
  enabled: true
  instrumentationMethod: env
  nsToInstrumentRegex: default
  defaultAppName: myk8s-application
  appNameStrategy: manual
  instrumentationRules:
    - namespaceRegex: default
      language: java
      labelMatch:
        - framework: java      
      imageInfo:
        image: docker.io/appdynamics/java-agent:latest
        agentMountPath: /opt/appdynamics
        imagePullPolicy: Always

# InfraViz config
infraViz:
  nodeOS: "linux"
  enableMasters: false
  stdoutLogging: true
  enableContainerHostId: true
  enableServerViz: true
  enableDockerViz: true

# Netviz config
netViz:
  enabled: true
  netVizPort: 3892
  