---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws
    version: 2.1

inputs:
  - name: input
run:
  path: /bin/sh
  args: ["./input/configure_iam.sh"]

